# Generated by Django 5.2.1 on 2025-05-19 19:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kunde',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('telefon', models.CharField(blank=True, max_length=20, null=True)),
                ('adresse', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Schienenabschnitt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schienentyp', models.CharField(blank=True, max_length=100, null=True)),
                ('schienenhaerte', models.PositiveIntegerField(blank=True, null=True)),
                ('maximale_geschwindigkeit', models.PositiveIntegerField(blank=True, null=True)),
                ('laenge', models.FloatField(blank=True, null=True)),
                ('kunde', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='verkaufstool.kunde')),
            ],
        ),
    ]
