# Generated by Django 5.2.1 on 2025-05-19 20:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verkaufstool', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schienenabschnitt',
            name='kunde',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schienenabschnitte', to='verkaufstool.kunde'),
        ),
    ]
