# Generated by Django 5.2.1 on 2025-05-23 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verkaufstool', '0002_alter_schienenabschnitt_kunde'),
    ]

    operations = [
        migrations.AddField(
            model_name='kunde',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='schienenabschnitt',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
