# Generated by Django 5.2.1 on 2025-05-29 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verkaufstool', '0003_kunde_updated_at_schienenabschnitt_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schienenabschnitt',
            name='laenge',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='schienenabschnitt',
            name='maximale_geschwindigkeit',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='schienenabschnitt',
            name='schienenhaerte',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='schienenabschnitt',
            name='schienentyp',
            field=models.CharField(max_length=100),
        ),
    ]
